//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parents.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Parents.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddChildFormTitle {
            get {
                return ResourceManager.GetString("AddChildFormTitle", resourceCulture);
            }
        }
        
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        internal static string CancelAction {
            get {
                return ResourceManager.GetString("CancelAction", resourceCulture);
            }
        }
        
        internal static string ChildFirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("ChildFirstNamePlaceHolder", resourceCulture);
            }
        }
        
        internal static string ChildIDCardPlaceHolder {
            get {
                return ResourceManager.GetString("ChildIDCardPlaceHolder", resourceCulture);
            }
        }
        
        internal static string ChildLastNameNamePlaceHolder {
            get {
                return ResourceManager.GetString("ChildLastNameNamePlaceHolder", resourceCulture);
            }
        }
        
        internal static string ChildListFormTitle {
            get {
                return ResourceManager.GetString("ChildListFormTitle", resourceCulture);
            }
        }
        
        internal static string ChildrensMenu {
            get {
                return ResourceManager.GetString("ChildrensMenu", resourceCulture);
            }
        }
        
        internal static string ConfigurationMenu {
            get {
                return ResourceManager.GetString("ConfigurationMenu", resourceCulture);
            }
        }
        
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static string ConfirmDeleteRecord {
            get {
                return ResourceManager.GetString("ConfirmDeleteRecord", resourceCulture);
            }
        }
        
        internal static string DialogErrorTitle {
            get {
                return ResourceManager.GetString("DialogErrorTitle", resourceCulture);
            }
        }
        
        internal static string DiaryMenu {
            get {
                return ResourceManager.GetString("DiaryMenu", resourceCulture);
            }
        }
        
        internal static string ErrorOcurredTryLater {
            get {
                return ResourceManager.GetString("ErrorOcurredTryLater", resourceCulture);
            }
        }
        
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Opening {
            get {
                return ResourceManager.GetString("Opening", resourceCulture);
            }
        }
        
        internal static string ParentsMenu {
            get {
                return ResourceManager.GetString("ParentsMenu", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        internal static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
